### ISSUE TITLE
What game to play next?

### ISSUE THREAD

**Issue by SwartzCr** [SwartzCr/grimfandango#1]
We need to pick a game to play next - we just finished Inside, Frog Fractions, and Oxenfree - time to do something new.

I hereby nominate Headlander as our next game, feel free to suggest other things in this issue

**Comment by koalahamlet** [comment]
:shipit:

**Comment by CLowbrow** [comment]
Headlander sounds good but it probably has the most mechanically challenging gameplay of anything we've done.

**Comment by CLowbrow** [comment]
Did people have feelings about [Gone Home](https://en.wikipedia.org/wiki/Gone_Home)? It's on our list and would probably be enjoyable for people who liked Obduction (I played the first 20 minutes).

**Comment by davidestes** [comment]
I'll throw in [Night in the Woods](http://www.nightinthewoods.com), though I've heard it's very similar to Oxenfree. Kona and I just played through the whole thing in two evenings, and it's probably my GOTY.

**Comment by SwartzCr** [comment]
@davidestes that's a great suggestion - you should add it to the list
@CLowbrow gone home is on the list but feel free to style it to stand out if you want
I'm going to close this issue since I think this is probably the totally wrong place to solicit suggestions - since like some people don't have GH accounts, I'm gonna move this conversation back to email
